In [1]:
import pickle as pkl
import numpy as np
import pandas as pd

testing by logistic regression


In [10]:

pipe1=pkl.load(open("stress_estimation_lr.pkl","rb"))

In [11]:
a=np.array([6.0,"Male","College","Average",7.5,3.0,69.0,8],dtype=object).reshape(1,8)
a


array([[6.0, 'Male', 'College', 'Average', 7.5, 3.0, 69.0, 8]],
      dtype=object)

In [12]:
a=pd.DataFrame(a,columns=["social_interaction_score","gender","student_type","sleep_quality","sleephoursimputed","screentimeimputedinhours","physicalactmins","moodscore"])

In [13]:
a

social_interaction_score gender student_type sleep_quality  \
0                      6.0   Male      College       Average   

  sleephoursimputed screentimeimputedinhours physicalactmins moodscore  
0               7.5                      3.0            69.0         8

In [14]:
pipe1.predict(a)

array([1])

In [15]:
b=np.array([5.2,"Male","Working","Poor",4.5,5.8,23.0,3],dtype=object).reshape(1,8)
a=pd.DataFrame(b,columns=["social_interaction_score","gender","student_type","sleep_quality","sleephoursimputed","screentimeimputedinhours","physicalactmins","moodscore"])


In [16]:
a

social_interaction_score gender student_type sleep_quality  \
0                      5.2   Male      Working          Poor   

  sleephoursimputed screentimeimputedinhours physicalactmins moodscore  
0               4.5                      5.8            23.0         3

In [17]:
pipe1.predict(a)

array([0])

testing by random forest

In [18]:
pipe2=pkl.load(open("stress_estimation_lr.pkl","rb"))

In [19]:
c=np.array([7.0,"Female","College","Average",7.5,3.0,69.0,8],dtype=object).reshape(1,8)
c=pd.DataFrame(c,columns=["social_interaction_score","gender","student_type","sleep_quality","sleephoursimputed","screentimeimputedinhours","physicalactmins","moodscore"])